from __future__ import annotations

import argparse
from decimal import Decimal
import secrets
from pathlib import Path
from typing import Sequence

from xrpl.clients import JsonRpcClient
from xrpl.wallet import Wallet

from devtools.live_testnet_support import (
    get_live_wallet_pair,
    resolve_live_testnet_rpc_url,
    wallet_cache_path,
)

DEFAULT_OUTPUT_PATH = Path(".env.quickstart")
DEFAULT_PRICE_DROPS = 1000
DEFAULT_REDIS_URL = "redis://127.0.0.1:6379/0"
DEFAULT_MPP_CHALLENGE_TTL_SECONDS = 300


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a reusable XRPL Testnet quickstart environment file for the "
            "facilitator, merchant, and buyer demo stack."
        ),
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help="Path to the generated Docker Compose env file",
    )
    parser.add_argument(
        "--price-drops",
        type=int,
        default=DEFAULT_PRICE_DROPS,
        help="XRP price for the demo merchant route, in drops",
    )
    parser.add_argument(
        "--facilitator-token",
        default=None,
        help="Optional facilitator bearer token to write instead of generating one",
    )
    parser.add_argument(
        "--xrpl-rpc-url",
        default=None,
        help=(
            "Optional XRPL Testnet JSON-RPC endpoint for wallet generation and the generated "
            ".env.quickstart file"
        ),
    )
    return parser


def render_quickstart_env(
    *,
    xrpl_rpc_url: str,
    merchant_wallet: Wallet,
    buyer_wallet: Wallet,
    facilitator_token: str,
    mpp_challenge_secret: str,
    price_drops: int,
) -> str:
    buyer_seed = buyer_wallet.seed
    if buyer_seed is None:
        raise RuntimeError("Buyer wallet is missing a seed")

    lines = [
        "# Generated by `python -m devtools.quickstart`.",
        "# Contains secrets for local XRPL Testnet demos. Do not commit this file.",
        "GATEWAY_AUTH_MODE=single_token",
        f"XRPL_RPC_URL={xrpl_rpc_url}",
        "NETWORK_ID=testnet",
        "XRPL_NETWORK=testnet",
        "SETTLEMENT_MODE=validated",
        f"MY_DESTINATION_ADDRESS={merchant_wallet.classic_address}",
        f"FACILITATOR_BEARER_TOKEN={facilitator_token}",
        f"REDIS_URL={DEFAULT_REDIS_URL}",
        f"XRPL_WALLET_SEED={buyer_seed}",
        f"XRPL_MPP_EXPECTED_RECIPIENT={merchant_wallet.classic_address}",
        f"XRPL_MPP_MAX_SPEND={format(Decimal(price_drops) / Decimal('1000000'), 'f')}",
        f"MPP_CHALLENGE_SECRET={mpp_challenge_secret}",
        f"MPP_CHALLENGE_TTL_SECONDS={DEFAULT_MPP_CHALLENGE_TTL_SECONDS}",
        f"PRICE_AMOUNT={price_drops}",
        "PRICE_CURRENCY=XRP",
        "PAYMENT_CURRENCY=XRP",
        "ALLOWED_ISSUED_ASSETS=",
        "ALLOWED_MPT_ISSUANCE_IDS=",
        "",
        "# Issued currencies use compact JSON on the MPP wire.",
        "# Generate ready-to-run variants with `python -m devtools.demo_env --asset rlusd`.",
        "",
    ]
    return "\n".join(lines)


def mask_secret(value: str, *, visible_prefix: int) -> str:
    visible = value[:visible_prefix]
    return f"{visible}{'*' * max(len(value) - len(visible), 0)}"


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    xrpl_rpc_url = resolve_live_testnet_rpc_url(args.xrpl_rpc_url)
    client = JsonRpcClient(xrpl_rpc_url)
    wallets = get_live_wallet_pair(client)
    merchant_wallet = wallets.wallet_a
    buyer_wallet = wallets.wallet_b

    facilitator_token = args.facilitator_token or secrets.token_urlsafe(24)
    mpp_challenge_secret = secrets.token_urlsafe(32)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_quickstart_env(
            xrpl_rpc_url=xrpl_rpc_url,
            merchant_wallet=merchant_wallet,
            buyer_wallet=buyer_wallet,
            facilitator_token=facilitator_token,
            mpp_challenge_secret=mpp_challenge_secret,
            price_drops=args.price_drops,
        ),
        encoding="utf-8",
    )

    buyer_seed = buyer_wallet.seed
    if buyer_seed is None:
        raise RuntimeError("Buyer wallet is missing a seed")

    print(f"Wrote {output_path}")
    print(f"Merchant address: {merchant_wallet.classic_address}")
    print(f"Buyer address: {buyer_wallet.classic_address}")
    print(f"Buyer seed: {mask_secret(buyer_seed, visible_prefix=3)}")
    print(f"XRPL RPC URL: {xrpl_rpc_url}")
    print(
        "Facilitator bearer token: "
        f"{mask_secret(facilitator_token, visible_prefix=2)}"
    )
    print(
        "MPP challenge secret: "
        f"{mask_secret(mpp_challenge_secret, visible_prefix=3)}"
    )
    print(f"Wallet cache: {wallet_cache_path()}")
    print("Next steps:")
    print(f"  docker compose --env-file {output_path} up --build")
    print(f"  docker compose --env-file {output_path} --profile demo run --rm buyer")
    print("Asset follow-ups:")
    print("  python -m devtools.rlusd_fund --target-rlusd 10 --max-xrp 35")
    print("  python -m devtools.usdc_topup")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
